/**
 * Created by lcc3536 on 14-6-11.
 */




var DISTANCE_EPSILON = 0.05;

var BATTLEFIELD_MIN_X = 0;
var BATTLEFIELD_MAX_X = 1136;

var HERO_TO_SOLDIER_MAX_DISTANCE = (BATTLEFIELD_MAX_X - BATTLEFIELD_MIN_X) / 2.5;

var HERO_POSITION_X_OWN = 80;
var HERO_POSITION_X_ENEMY = 1056;

var SOLDIER_POSITION_X_OWN = -50;
var SOLDIER_POSITION_X_ENEMY = 1186;

var DEFAULT_FLOOR_HEIGHT = 230;
var DEFAULT_PASS_LIMIT_X = 80;

var FORCE_TYPE = {
    WIND_FORCE: 0
};

var DEFAULT_FORCE = {};
DEFAULT_FORCE[FORCE_TYPE.WIND_FORCE] = op.f(0, 0);

var ACCELERATION_TYPE = {
    GRAVITATIONAL_ACCELERATION: 0
};

var DEFAULT_ACCELERATION = {};
DEFAULT_ACCELERATION[ACCELERATION_TYPE.GRAVITATIONAL_ACCELERATION] = op.a(0, -980);

var DEFAULT_HERO_POSITION = {};
DEFAULT_HERO_POSITION[TEAM_TYPE_CONFIG.OWN] = cc.p(HERO_POSITION_X_OWN, DEFAULT_FLOOR_HEIGHT);
DEFAULT_HERO_POSITION[TEAM_TYPE_CONFIG.ENEMY] = cc.p(HERO_POSITION_X_ENEMY, DEFAULT_FLOOR_HEIGHT);

var DEFAULT_SOLDIER_POSITION = {};
DEFAULT_SOLDIER_POSITION[TEAM_TYPE_CONFIG.OWN] = cc.p(SOLDIER_POSITION_X_OWN, DEFAULT_FLOOR_HEIGHT);
DEFAULT_SOLDIER_POSITION[TEAM_TYPE_CONFIG.ENEMY] = cc.p(SOLDIER_POSITION_X_ENEMY, DEFAULT_FLOOR_HEIGHT);

var DEFAULT_SOLDIER_CRITICAL_POINT = {};
DEFAULT_SOLDIER_CRITICAL_POINT[TEAM_TYPE_CONFIG.OWN] = cc.p(HERO_POSITION_X_OWN, DEFAULT_FLOOR_HEIGHT);
DEFAULT_SOLDIER_CRITICAL_POINT[TEAM_TYPE_CONFIG.ENEMY] = cc.p(HERO_POSITION_X_ENEMY, DEFAULT_FLOOR_HEIGHT);

var DEFAULT_SOLDIER_X_RANGE = {};
DEFAULT_SOLDIER_X_RANGE[TEAM_TYPE_CONFIG.OWN] = {min: SOLDIER_POSITION_X_OWN, max: 1136};
DEFAULT_SOLDIER_X_RANGE[TEAM_TYPE_CONFIG.ENEMY] = {min: 0, max: SOLDIER_POSITION_X_ENEMY};