/**
 * Created by lcc3536 on 14-6-28.
 */


var STATUS_TO_MOVEMENT_ID = {};

STATUS_TO_MOVEMENT_ID[STATUS_CONFIG.DEFAULT] = "";
STATUS_TO_MOVEMENT_ID[STATUS_CONFIG.BEGAN] = "began";
STATUS_TO_MOVEMENT_ID[STATUS_CONFIG.IDLE] = "idle";
STATUS_TO_MOVEMENT_ID[STATUS_CONFIG.MOVE] = "move";
STATUS_TO_MOVEMENT_ID[STATUS_CONFIG.ATTACK] = "attack";
STATUS_TO_MOVEMENT_ID[STATUS_CONFIG.HURT] = "hurt";
STATUS_TO_MOVEMENT_ID[STATUS_CONFIG.DIED] = "died";
STATUS_TO_MOVEMENT_ID[STATUS_CONFIG.STIFF] = "";
STATUS_TO_MOVEMENT_ID[STATUS_CONFIG.READY] = "ready_";
STATUS_TO_MOVEMENT_ID[STATUS_CONFIG.LAUNCH] = "launch_";